source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

inhibit_all_warnings!
use_frameworks!

target 'Shock_Example' do
  pod 'Shock', :path => '../'
  
  pod 'JustLog', '3.1.3'

  target 'Shock_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
  end
end