source 'https://cdn.cocoapods.org/'

platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

target 'Shock_Example' do
  pod 'Shock', :path => '../'
  
  pod 'JustLog', '3.1.3'

  target 'Shock_Tests' do
    inherit! :search_paths
  end
end
