// swift-tools-version: 5.7

// This file was automatically generated by PackageGenerator and untracked
// PLEASE DO NOT EDIT MANUALLY

import PackageDescription

let package = Package(
    name: "Shock",
    defaultLocalization: "en",
    platforms: [.iOS(.v15)],
    products: [
        .library(
            name: "Shock",
            targets: ["Shock"]
        ),
    ],
    dependencies: [
        .package(
            url: "https://github.com/groue/GRMustache.swift",
            exact: "4.1.0"
        ),
        .package(
            url: "https://github.com/apple/swift-nio",
            exact: "2.51.0"
        ),
    ],
    targets: [
        .target(
            name: "Shock",
            dependencies: [
                .product(name: "NIO", package: "swift-nio"),
                .product(name: "NIOConcurrencyHelpers", package: "swift-nio"),
                .product(name: "NIOHTTP1", package: "swift-nio"),
                .product(name: "Mustache", package: "GRMustache.swift")
            ],
            path: "Framework/Sources"
        ),
        .testTarget(
            name: "ShockTests",
            dependencies: [
                .byName(name: "Shock"),
            ],
            path: "Tests/Sources",
            resources: [
                .process("Resources")
            ]
        ),
    ]
)
