default_platform :ios

platform :ios do

    before_all do
        ensure_bundle_exec
        $common_test_xcargs = "COMPILER_INDEX_STORE_ENABLE=NO"
        $derived_data_folder = "./derived_data"
        $scheme = "Shock"
        $test_output_folder = "fastlane/test_output"
    end

    lane :unit_tests do |parameters|
        UI.user_error! "Missing parameter 'device'" unless parameters.has_key?(:device)
        device = parameters[:device]
        
        # Build for testing
        run_tests(
            package_path: './',
            scheme: $scheme,
            device: device,
            code_coverage: true,
            result_bundle: true,
            concurrent_workers: 1,
            xcargs: $common_test_xcargs,
            derived_data_path: $derived_data_folder,
            output_directory: $test_output_folder,
            build_for_testing: true
        )
        # Test without building
        run_tests(
            package_path: './',
            scheme: $scheme,
            device: device,
            code_coverage: true,
            result_bundle: true,
            concurrent_workers: 1,
            xcargs: $common_test_xcargs,
            derived_data_path: $derived_data_folder,
            output_directory: $test_output_folder,
            test_without_building: true
        )
    end

end
